// <auto-generated />
using System;
using Corelio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corelio.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corelio.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("ChangedFields")
                        .HasColumnType("text[]")
                        .HasColumnName("changed_fields");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("request_path");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("success");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_email");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("user_ip");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_id")
                        .HasFilter("entity_id IS NOT NULL");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_audit_logs_event_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_logs_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("TenantId", "EntityType", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_entity_created");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDangerous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_dangerous");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_permissions_module");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Code = "users.view",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View user list",
                            IsDangerous = false,
                            Module = "Users",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111112"),
                            Code = "users.create",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new users",
                            IsDangerous = false,
                            Module = "Users",
                            Name = "Create Users"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111113"),
                            Code = "users.edit",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit user details",
                            IsDangerous = false,
                            Module = "Users",
                            Name = "Edit Users"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111114"),
                            Code = "users.delete",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete users",
                            IsDangerous = true,
                            Module = "Users",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222221"),
                            Code = "products.view",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View product list",
                            IsDangerous = false,
                            Module = "Products",
                            Name = "View Products"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Code = "products.create",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new products",
                            IsDangerous = false,
                            Module = "Products",
                            Name = "Create Products"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222223"),
                            Code = "products.edit",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit product details",
                            IsDangerous = false,
                            Module = "Products",
                            Name = "Edit Products"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222224"),
                            Code = "products.delete",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete products",
                            IsDangerous = false,
                            Module = "Products",
                            Name = "Delete Products"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333331"),
                            Code = "sales.view",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View sales transactions",
                            IsDangerous = false,
                            Module = "Sales",
                            Name = "View Sales"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333332"),
                            Code = "sales.create",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new sales",
                            IsDangerous = false,
                            Module = "Sales",
                            Name = "Create Sales"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Code = "sales.cancel",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cancel sales transactions",
                            IsDangerous = true,
                            Module = "Sales",
                            Name = "Cancel Sales"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444441"),
                            Code = "inventory.view",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View inventory levels",
                            IsDangerous = false,
                            Module = "Inventory",
                            Name = "View Inventory"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444442"),
                            Code = "inventory.adjust",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjust inventory levels",
                            IsDangerous = false,
                            Module = "Inventory",
                            Name = "Adjust Inventory"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555551"),
                            Code = "reports.view",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View business reports",
                            IsDangerous = false,
                            Module = "Reports",
                            Name = "View Reports"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555552"),
                            Code = "reports.export",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Export reports to file",
                            IsDangerous = false,
                            Module = "Reports",
                            Name = "Export Reports"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666661"),
                            Code = "settings.view",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View system settings",
                            IsDangerous = false,
                            Module = "Settings",
                            Name = "View Settings"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666662"),
                            Code = "settings.edit",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modify system settings",
                            IsDangerous = true,
                            Module = "Settings",
                            Name = "Edit Settings"
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("barcode_type");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("CostPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("ImagesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("images_json");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBundle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bundle");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_service");

                    b.Property<bool>("IsTaxExempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_tax_exempt");

                    b.Property<bool>("IsVariantParent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_variant_parent");

                    b.Property<decimal?>("LengthCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("length_cm");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<decimal?>("MaxStockLevel")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("max_stock_level");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_keywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_title");

                    b.Property<decimal>("MinStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_stock_level");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_number");

                    b.Property<decimal?>("Msrp")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("msrp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("primary_image_url");

                    b.Property<decimal?>("ReorderPoint")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("reorder_point");

                    b.Property<decimal?>("ReorderQuantity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("reorder_quantity");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("SatHazardousMaterial")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("sat_hazardous_material");

                    b.Property<string>("SatProductCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("sat_product_code");

                    b.Property<string>("SatUnitCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("sat_unit_code");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<decimal>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.1600m)
                        .HasColumnName("tax_rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TrackInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("track_inventory");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal?>("VolumeCm3")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("volume_cm3");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("weight_kg");

                    b.Property<decimal?>("WholesalePrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("wholesale_price");

                    b.Property<decimal?>("WidthCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("width_cm");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_products_is_active");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("ix_products_is_featured")
                        .HasFilter("is_featured = true AND is_deleted = false");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_barcode")
                        .HasFilter("barcode IS NOT NULL AND is_deleted = false");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_sku")
                        .HasFilter("is_deleted = false");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Corelio.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon_name");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_product_categories_is_active");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_product_categories_parent_id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_product_categories_path");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_categories_tenant_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_tenant_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("Corelio.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jti");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("use_count");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_is_revoked");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_jti");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_refresh_tokens_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsSystemRole")
                        .HasDatabaseName("ix_roles_is_system_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_roles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            IsDefault = false,
                            IsSystemRole = true,
                            Name = "Administrator",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Store manager with most permissions",
                            IsDefault = false,
                            IsSystemRole = false,
                            Name = "Manager",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Point of sale operator",
                            IsDefault = true,
                            IsSystemRole = false,
                            Name = "Cashier",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permissions_role_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111112"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111113"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111114"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222221"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222223"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222224"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333331"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333332"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a4444444-4444-4444-4444-444444444441"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a4444444-4444-4444-4444-444444444442"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a5555555-5555-5555-5555-555555555551"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a5555555-5555-5555-5555-555555555552"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a6666666-6666-6666-6666-666666666661"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("a6666666-6666-6666-6666-666666666662"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111112"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a1111111-1111-1111-1111-111111111113"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222221"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222223"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222224"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333331"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333332"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a4444444-4444-4444-4444-444444444441"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a4444444-4444-4444-4444-444444444442"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a5555555-5555-5555-5555-555555555551"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a5555555-5555-5555-5555-555555555552"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("a6666666-6666-6666-6666-666666666661"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("a2222222-2222-2222-2222-222222222221"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333331"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("a3333333-3333-3333-3333-333333333332"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("a4444444-4444-4444-4444-444444444441"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_domain");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTrial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trial");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_name");

                    b.Property<int>("MaxProducts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("max_products");

                    b.Property<int>("MaxSalesPerMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5000)
                        .HasColumnName("max_sales_per_month");

                    b.Property<int>("MaxUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_users");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subdomain");

                    b.Property<DateTime?>("SubscriptionEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_ends_at");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subscription_plan");

                    b.Property<DateTime>("SubscriptionStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_starts_at");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_custom_domain")
                        .HasFilter("custom_domain IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tenants_is_active");

                    b.HasIndex("Rfc")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_rfc");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_subdomain");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsTrial = true,
                            LegalName = "Ferretería Demo S.A. de C.V.",
                            MaxProducts = 5000,
                            MaxSalesPerMonth = 10000,
                            MaxUsers = 10,
                            Name = "Demo Hardware Store",
                            Rfc = "FDE010101ABC",
                            Subdomain = "demo",
                            SubscriptionPlan = "Premium",
                            SubscriptionStartsAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            TrialEndsAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.TenantConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowNegativeInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_negative_inventory");

                    b.Property<bool>("AutoCalculateMargin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_calculate_margin");

                    b.Property<TimeOnly?>("BusinessHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("business_hours_end");

                    b.Property<TimeOnly?>("BusinessHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("business_hours_start");

                    b.Property<DateTime?>("CfdiCertificateExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cfdi_certificate_expires_at");

                    b.Property<string>("CfdiCertificatePassword")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cfdi_certificate_password");

                    b.Property<string>("CfdiCertificatePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cfdi_certificate_path");

                    b.Property<string>("CfdiKeyPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cfdi_key_path");

                    b.Property<int>("CfdiNextFolio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cfdi_next_folio");

                    b.Property<string>("CfdiPacApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cfdi_pac_api_key");

                    b.Property<string>("CfdiPacApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cfdi_pac_api_url");

                    b.Property<string>("CfdiPacProvider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cfdi_pac_provider");

                    b.Property<bool>("CfdiPacTestMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("cfdi_pac_test_mode");

                    b.Property<string>("CfdiSeries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("A")
                        .HasColumnName("cfdi_series");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("MXN")
                        .HasColumnName("currency");

                    b.Property<decimal>("DefaultTaxRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.1600m)
                        .HasColumnName("default_tax_rate");

                    b.Property<Guid?>("DefaultWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_warehouse_id");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_notifications_enabled");

                    b.Property<bool>("FeatureEcommerce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("feature_ecommerce");

                    b.Property<bool>("FeatureLoyaltyProgram")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("feature_loyalty_program");

                    b.Property<bool>("FeatureMultiWarehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("feature_multi_warehouse");

                    b.Property<bool>("FeaturePurchaseOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("feature_purchase_orders");

                    b.Property<decimal>("LowStockNotificationThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(20.00m)
                        .HasColumnName("low_stock_notification_threshold");

                    b.Property<bool>("PosAutoPrintReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pos_auto_print_receipt");

                    b.Property<string>("PosDefaultPaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Cash")
                        .HasColumnName("pos_default_payment_method");

                    b.Property<bool>("PosEnableBarcodeScanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("pos_enable_barcode_scanner");

                    b.Property<string>("PosReceiptFooter")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pos_receipt_footer");

                    b.Property<bool>("PosRequireCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pos_require_customer");

                    b.Property<string>("PosThermalPrinterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pos_thermal_printer_name");

                    b.Property<bool>("RequireProductCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("require_product_cost");

                    b.Property<bool>("SmsNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sms_notifications_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("America/Mexico_City")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_configurations_tenant_id");

                    b.ToTable("tenant_configurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            AllowNegativeInventory = false,
                            AutoCalculateMargin = true,
                            BusinessHoursEnd = new TimeOnly(18, 0, 0),
                            BusinessHoursStart = new TimeOnly(9, 0, 0),
                            CfdiNextFolio = 1,
                            CfdiPacTestMode = true,
                            CfdiSeries = "A",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            DefaultTaxRate = 0.1600m,
                            EmailNotificationsEnabled = true,
                            FeatureEcommerce = false,
                            FeatureLoyaltyProgram = false,
                            FeatureMultiWarehouse = false,
                            FeaturePurchaseOrders = false,
                            LowStockNotificationThreshold = 20.00m,
                            PosAutoPrintReceipt = false,
                            PosDefaultPaymentMethod = "Cash",
                            PosEnableBarcodeScanner = true,
                            PosRequireCustomer = false,
                            RequireProductCost = true,
                            SmsNotificationsEnabled = false,
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Timezone = "America/Mexico_City",
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("email_confirmation_token");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_confirmed");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_login_ip");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_reset_token");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_email");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@demo.corelio.app",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "User",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIq7MRnH.m",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = ""
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@demo.corelio.app",
                            FailedLoginAttempts = 0,
                            FirstName = "Manager",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "User",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIq7MRnH.m",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = ""
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cashier@demo.corelio.app",
                            FailedLoginAttempts = 0,
                            FirstName = "Cashier",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "User",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIq7MRnH.m",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = ""
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_roles_expires_at")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            RoleId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            RoleId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            RoleId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            AssignedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Product", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.ProductCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Role", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corelio.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.TenantConfiguration", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Configuration")
                        .HasForeignKey("Corelio.Domain.Entities.TenantConfiguration", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.User", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Corelio.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corelio.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Corelio.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
